AllCops:
  Exclude:
  - 'bin/**/*'
  - 'db/schema.rb'
  - 'script/**/*'
  - 'vendor/**/*'
  TargetRubyVersion: 2.6

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 160

Style/Documentation:
  Enabled: false
